[package]
name="git-discovery"
version="0.0.0"
edition="2024"
[workspace]
[dependencies]
rnx={git="https://github.com/nilket-com/rnx",rev="94f5f3f98ba756c5ab5293d1e5132c7fd7b52d32"}
rnx-polars={git="https://github.com/nilket-com/rnx",rev="94f5f3f98ba756c5ab5293d1e5132c7fd7b52d32"}
rnx-postgres={git="https://github.com/nilket-com/rnx",rev="94f5f3f98ba756c5ab5293d1e5132c7fd7b52d32"}
