import collections,json,pathlib,statistics,math
P=pathlib.Path(__file__).resolve().parent;O=P.parents[1]/'results/lua-rust-0001'
rows=[json.loads(l) for l in (O/'samples.jsonl').read_text().splitlines()];groups=collections.defaultdict(list)
subjects={'piccolo','omnilua','lua54','luajit','rnx-run','rnx-eval','python'};works={'empty','answer','numeric','strings','fib','answer-unpinned'}
seen=set()
for r in rows:
 assert set(r)=={'subject','work','repeat','sample','ns','affinity'};assert r['subject'] in subjects and r['work'] in works and type(r['ns']) is int and r['ns']>0
 key=(r['subject'],r['work'],r['repeat'],r['sample']);assert key not in seen;seen.add(key);groups[r['subject'],r['work']].append(r)
assert len(groups)==42 and len(rows)==1785
stats={}
for (s,w),rs in groups.items():
 repeats=1 if w=='answer-unpinned' else 3;count=30 if w in ['empty','answer','answer-unpinned'] else 5
 assert {(r['repeat'],r['sample']) for r in rs}=={(i,j) for i in range(repeats) for j in range(count)}
 assert all(r['affinity']==([4] if w!='answer-unpinned' else json.loads((O/'conditions.json').read_text())['original_affinity']) for r in rs)
 v=sorted(r['ns']/1e6 for r in rs)
 stats[s+'/'+w]=dict(n=len(v),mean_ms=statistics.mean(v),median_ms=statistics.median(v),min_ms=min(v),p10_ms=v[math.ceil(.1*len(v))-1],p90_ms=v[math.ceil(.9*len(v))-1],round_medians_ms=[statistics.median(r['ns']/1e6 for r in rs if r['repeat']==i) for i in range(repeats)])
(O/'summary.json').write_text(json.dumps(stats,indent=2,sort_keys=True)+'\n')
md='# Rust Lua CLI probe\n\nPiccolo and omniLua both deliver sub-millisecond warm, pinned source-to-answer startup here. Piccolo is slower on numeric/recursive VM work; this does not establish how native Polars/Candle bindings would perform. Lua remains an additional possible project, with rnx unchanged.\n\n## Pinned wall time\n\nMedian milliseconds, including process startup and source parsing/compilation. Sustained rows are end-to-end fixed-size workloads, not VM-only clocks; no startup cost is subtracted.\n\n| Subject | Empty script | Print 42 | Numeric loop | Strings/table | fib(27) |\n|---|---:|---:|---:|---:|---:|\n'
order=['lua54','luajit','piccolo','omnilua','rnx-run','rnx-eval','python']
for s in order:md+='| '+s+' | '+' | '.join(f"{stats[s+'/'+w]['median_ms']:.3f}" for w in ['empty','answer','numeric','strings','fib'])+' |\n'
md+='\nAll 1,785 timed invocations validated exit status, empty stderr and exact expected stdout. Startup/42: 5 warmups, 90 samples each; sustained: 2 warmups, 15 samples each. Three seeded shuffled rounds; raw samples, round medians and distribution summaries retained. This tiny suite does not verify a project’s general speed claim.\n\n## Unpinned source-to-answer control\n\nSeparate later 30-sample runs, five warmups; these are not interleaved with the pinned run.\n\n| Subject | Median ms |\n|---|---:|\n'
for s in order:md+=f"| {s} | {stats[s+'/answer-unpinned']['median_ms']:.3f} |\n"
md+='\nIntel i7-14700 hybrid CPU, Linux; initial comparison pinned to core 4, unpinned controls allow cores 0–27. Governor powersave, intel_pstate; recorded frequency policy does not establish actual execution frequency. Scheduling, migration and changing host load are plausible unmeasured explanations for slower unpinned runs.\n\n## Peak RSS\n\nKiB, one separate /usr/bin/time pass per subject/workload, not a statistical memory bound and not part of the timed clock.\n\n| Subject | Empty | 42 | Numeric | Strings | fib |\n|---|---:|---:|---:|---:|---:|\n'
rss={(r['subject'],r['work']):r['maxrss_kib'] for r in json.loads((O/'rss.json').read_text())}
for s in order:md+='| '+s+' | '+' | '.join(str(rss[s,w]) for w in ['empty','answer','numeric','strings','fib'])+' |\n'
md+='\n## Binaries and builds\n\n| Subject | Binary bytes |\n|---|---:|\n'
b=json.loads((O/'conditions.json').read_text())['binaries']
for s in order:md+=f"| {s} | {b[s]['bytes']} |\n"
for r in json.loads((O/'builds.json').read_text()):md+=f"\n{r['name']} release build/install from an empty target: {r['seconds']:.2f} s."
md+='\n\nOne build each, no precision comparison implied; package downloads/index updates included, OS and existing Cargo caches warm. Piccolo’s own unmodified interpreter example at ce709eb1dae5c543cbc78e7e12bb80249d88c55f; omniLua CLI 0.7.1, packaged lockfile, default features, OMNILUA_VERSION=5.4 explicitly (also its default). Binary/compiler/lock hashes and full build logs retained. No LTO/PGO/allocator tweaks. rnx uses the stock 0167 binary, not the older installed cargo-bin copy.\n\n## Shipped functionality\n\nPresence below means the global table exists, not that every member is implemented. Piccolo’s example initializes Lua::full(), its load_io installs print rather than a standard io table. The measured CLI has no io table, os table, utf8 table or require.\n\n'
libs=json.loads((O/'libraries.json').read_text())
md+='| Subject | string | table | math | io | os | utf8 | coroutine | require |\n|---|---|---|---|---|---|---|---|---|\n'
for s in ['piccolo','omnilua','lua54','luajit']:
 d=dict(line.split(':',1) for line in libs[s].splitlines());md+='| '+s+' | '+' | '.join(d[k] for k in ['string','table','math','io','os','utf8','coroutine','require'])+' |\n'
md+='\nNo json/cjson/dkjson module resolved in any measured Lua CLI environment; no module was added. Python and rnx shipped JSON round-trip functionality was checked separately (json-capabilities.json), not used to manufacture a cross-language timing comparison.\n\nPiccolo has an existing file runner and REPL (-r enters REPL after file); no -e eval switch. omniLua, PUC Lua and LuaJIT supply file/REPL/-e; rnx supplies run/eval/session; Python supplies file/-c/REPL. CLI source inspection establishes REPL availability; interactive behavior is not benchmarked.\n\n## Interpretation and limits\n\nPiccolo is a believable candidate for the next small vertical slice: warm startup is close to omniLua and much smaller than rnx/Python here. Its recursive fixture takes about twice rnx’s time; pure VM throughput and library completeness are real tradeoffs. The numeric loop uses modulo each iteration; LuaJIT’s result here is not a general JIT verdict. All runtimes produce the same independently calculated answers, with exact small integers. Rune gathers identical strings then appends delimiters because it lacks Vec.join; Lua uses table.concat and Python str.join. Those API implementations differ, so this is a functionality workload, not a claim of identical allocation strategies.\n\nPiccolo fuel bounds VM work, not long native adapter calls; this probe measures no userdata bridge, cancellation, callbacks, or Polars/Candle operation. A separate-project vertical slice requires the user’s decision.\n\nThe lua-rs repository URL redirects to omniLua and the published crate metadata uses the new name; that rename is verified. Full upstream Lua conformance and the project’s published aggregate speed claims remain unverified: no full upstream suite was run here. Selected fixtures passing is not conformance certification.\n\n## Clock and attempts\n\nNative helper reused byte-for-byte from rustc-42: command setup/helper startup outside Instant, spawn, stdout/stderr pipe capture and blocking wait inside; no shell or overhead subtraction. Contemporary hyperfine -N and native preflight on true/cached Rust passed within 0.15 ms; full samples retained in preflight.json. The driver ran under an external 600-second timeout with five-second kill grace.\n\nsetup-attempt1 stopped before timing: the library discovery script used _G, which Piccolo lacks. Discovery was changed to explicit globals; all workload validations had already passed. The attempt’s preflight and validations are retained. The deciding attempt completed without any sample removal or configuration tuning.\n'
(O/'summary.md').write_text(md)
