[package]
name = "rune-base-new"
version = "0.0.0"
edition = "2024"
[workspace]
[features]
allocation = []
counter = []
[dependencies]
rune = { path = "/home/me/work/rune-w2-0172/crates/rune", default-features = false, features = ["std", "fmt", "anyhow"] }
futures = "0.3"
[profile.release]
opt-level = 3
