// Public-only diagnostic: private hash_map/hash_set/vec_deque modules excluded.
fn registration() {
 let mut context=rune::Context::new();
 let mut rows=Vec::with_capacity(34);
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::iter::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("iter",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::core::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("core",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::cmp::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("cmp",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::any::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("any",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::clone::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("clone",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::num::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("num",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::hash::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("hash",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::string::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("string",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::bytes::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("bytes",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::collections::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("collections",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::char::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("char",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::f64::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("f64",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::f64::consts::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("f64::consts",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::tuple::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("tuple",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::fmt::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("fmt",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::future::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("future",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::i64::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("i64",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::u64::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("u64",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::io::module(true).unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("io",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::macros::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("macros",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::macros::builtin::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("macros::builtin",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::mem::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("mem",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::object::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("object",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::ops::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("ops",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::ops::generator::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("ops::generator",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::option::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("option",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::result::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("result",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::stream::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("stream",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::test::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("test",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::vec::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("vec",construct,install,a,b)); }
 { alloc_track::reset(); let t=std::time::Instant::now(); let module=rune::modules::slice::module().unwrap(); let construct=t.elapsed().as_nanos(); let a=alloc_track::snapshot(); alloc_track::reset(); let t=std::time::Instant::now();context.install(module).unwrap();let install=t.elapsed().as_nanos();let b=alloc_track::snapshot();rows.push(("slice",construct,install,a,b)); }
 let t=std::time::Instant::now();drop(context);let dropped=t.elapsed().as_nanos();
 for (name,c,i,a,b) in rows { eprintln!("MODULE {name} {c} {i} {a:?} {b:?}"); } eprintln!("REGDROP {dropped}");
}
