[package]
name = "interp-new"
version = "0.0.0"
edition = "2024"
[workspace]
[features]
allocation = []
counter = []
[dependencies]
rune = { path = "/home/me/work/rune/crates/rune", default-features = false, features = ["std", "fmt", "anyhow"] }
futures = "0.3"
[profile.release]
opt-level = 3
[profile.profiling]
inherits = "release"
debug = "line-tables-only"

[profile.profiling2]
inherits = "release"
debug = "line-tables-only"
