format=1
[application]
entry="entry.rn"
[runtime]
path="/home/me/work/rnx-bench/probes/removal-ownership/target/real/data ' private/rnx/runtimes/entries/54430e47250ac6fba8c7d96573057ab016d93917c0f8f30da2f2c06f05272a93/source"
[native.keep]
path="../keep"
package="keep-adapter"
builder="build"
hook="plain"


[native.polars]
path = "/home/me/work/rnx-bench/probes/removal-ownership/target/real/data ' private/rnx/runtimes/entries/54430e47250ac6fba8c7d96573057ab016d93917c0f8f30da2f2c06f05272a93/source/adapters/polars"
package = "rnx-polars"
builder = "build"
hook = "plain"
