format=1
[application]
entry="entry.rn"
[runtime]
path="/home/me/work/rnx-bench/probes/removal-ownership/target/real/data ' private/rnx/runtimes/entries/442b4f457ecefa68f57689994d2985e45e60d3cc43b6861081c51b3344f6ef6d/source"


[native.polars]
path = "/home/me/work/rnx-bench/probes/removal-ownership/target/real/data ' private/rnx/runtimes/entries/442b4f457ecefa68f57689994d2985e45e60d3cc43b6861081c51b3344f6ef6d/source/adapters/polars"
package = "rnx-polars"
builder = "build"
hook = "plain"
